/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Auth Health */
        get: operations["auth_health_api_v1_auth_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login User */
        post: operations["login_user_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Token */
        post: operations["refresh_token_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout User */
        post: operations["logout_user_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current User */
        get: operations["current_user_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Forgot Password */
        post: operations["forgot_password_api_v1_auth_password_forgot_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Password */
        post: operations["change_password_api_v1_auth_password_change_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/email/verification/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resend Email Verification */
        post: operations["resend_email_verification_api_v1_auth_email_verification_resend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/email/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Email */
        post: operations["verify_email_api_v1_auth_email_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Password */
        post: operations["reset_password_api_v1_auth_password_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bitacora": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Audit Logs */
        get: operations["list_audit_logs_api_v1_bitacora_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bitacora/{audit_log_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Audit Log */
        get: operations["get_audit_log_api_v1_bitacora__audit_log_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/empresa/parametros": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Parametros Empresa */
        get: operations["listar_parametros_empresa_api_v1_empresa_parametros_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/empresa/parametros/{codigo}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Actualizar Parametro Empresa */
        put: operations["actualizar_parametro_empresa_api_v1_empresa_parametros__codigo__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mi-empresa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Empresa */
        get: operations["get_my_empresa_api_v1_mi_empresa_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update My Empresa */
        patch: operations["update_my_empresa_api_v1_mi_empresa_patch"];
        trace?: never;
    };
    "/api/v1/mi-empresa/suscripcion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Subscription */
        get: operations["get_my_subscription_api_v1_mi_empresa_suscripcion_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mi-empresa/parametros": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Parameters */
        get: operations["list_my_parameters_api_v1_mi_empresa_parametros_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mi-empresa/parametros/{codigo}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update My Parameter */
        put: operations["update_my_parameter_api_v1_mi_empresa_parametros__codigo__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Platform Login */
        post: operations["platform_login_api_v1_platform_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Platform Refresh */
        post: operations["platform_refresh_api_v1_platform_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Platform Logout */
        post: operations["platform_logout_api_v1_platform_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Platform Me */
        get: operations["platform_me_api_v1_platform_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform/auth/password/change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Platform Change Password */
        post: operations["platform_change_password_api_v1_platform_auth_password_change_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform/empresas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Empresas */
        get: operations["list_empresas_api_v1_platform_empresas_get"];
        put?: never;
        /** Provision Empresa */
        post: operations["provision_empresa_api_v1_platform_empresas_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform/empresas/{empresa_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Empresa */
        get: operations["get_empresa_api_v1_platform_empresas__empresa_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Empresa */
        patch: operations["update_empresa_api_v1_platform_empresas__empresa_id__patch"];
        trace?: never;
    };
    "/api/v1/platform/empresas/{empresa_id}/activar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Activate Empresa */
        patch: operations["activate_empresa_api_v1_platform_empresas__empresa_id__activar_patch"];
        trace?: never;
    };
    "/api/v1/platform/empresas/{empresa_id}/suspender": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Suspend Empresa */
        patch: operations["suspend_empresa_api_v1_platform_empresas__empresa_id__suspender_patch"];
        trace?: never;
    };
    "/api/v1/platform/planes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Planes */
        get: operations["list_planes_api_v1_platform_planes_get"];
        put?: never;
        /** Create Plan */
        post: operations["create_plan_api_v1_platform_planes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform/planes/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Plan */
        get: operations["get_plan_api_v1_platform_planes__plan_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Plan */
        patch: operations["update_plan_api_v1_platform_planes__plan_id__patch"];
        trace?: never;
    };
    "/api/v1/platform/suscripciones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Subscriptions */
        get: operations["list_subscriptions_api_v1_platform_suscripciones_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform/empresas/{empresa_id}/suscripcion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Subscription */
        get: operations["get_subscription_api_v1_platform_empresas__empresa_id__suscripcion_get"];
        /** Replace Subscription */
        put: operations["replace_subscription_api_v1_platform_empresas__empresa_id__suscripcion_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform/bitacora": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Platform Audit */
        get: operations["list_platform_audit_api_v1_platform_bitacora_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform/bitacora/{audit_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Platform Audit */
        get: operations["get_platform_audit_api_v1_platform_bitacora__audit_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Roles */
        get: operations["list_roles_api_v1_roles_get"];
        put?: never;
        /** Create Role */
        post: operations["create_role_api_v1_roles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles/{role_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Role */
        get: operations["get_role_api_v1_roles__role_id__get"];
        put?: never;
        post?: never;
        /** Delete Role */
        delete: operations["delete_role_api_v1_roles__role_id__delete"];
        options?: never;
        head?: never;
        /** Update Role */
        patch: operations["update_role_api_v1_roles__role_id__patch"];
        trace?: never;
    };
    "/api/v1/roles/{role_id}/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Assign Permissions */
        put: operations["assign_permissions_api_v1_roles__role_id__permissions_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/usuarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Usuarios */
        get: operations["listar_usuarios_api_v1_usuarios_get"];
        put?: never;
        /** Crear Usuario */
        post: operations["crear_usuario_api_v1_usuarios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/usuarios/{usuario_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener Usuario */
        get: operations["obtener_usuario_api_v1_usuarios__usuario_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Actualizar Usuario */
        patch: operations["actualizar_usuario_api_v1_usuarios__usuario_id__patch"];
        trace?: never;
    };
    "/api/v1/usuarios/{usuario_id}/activar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Activar Usuario */
        patch: operations["activar_usuario_api_v1_usuarios__usuario_id__activar_patch"];
        trace?: never;
    };
    "/api/v1/usuarios/{usuario_id}/desactivar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Desactivar Usuario */
        patch: operations["desactivar_usuario_api_v1_usuarios__usuario_id__desactivar_patch"];
        trace?: never;
    };
    "/api/v1/usuarios/{usuario_id}/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Cambiar Password Usuario */
        put: operations["cambiar_password_usuario_api_v1_usuarios__usuario_id__password_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/usuarios/{usuario_id}/desbloquear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Desbloquear Usuario */
        patch: operations["desbloquear_usuario_api_v1_usuarios__usuario_id__desbloquear_patch"];
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Root */
        get: operations["read_root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActualizarParametroEmpresaRequest */
        ActualizarParametroEmpresaRequest: {
            /** Valor */
            valor: number | string;
            /**
             * Vigente Desde
             * Format: date
             */
            vigente_desde: string;
            /** Vigente Hasta */
            vigente_hasta?: string | null;
            /** Norma Legal */
            norma_legal?: string | null;
        };
        /** ActualizarUsuarioRequest */
        ActualizarUsuarioRequest: {
            /** Nombre */
            nombre?: string | null;
            /** Apellido */
            apellido?: string | null;
            /** Email */
            email?: string | null;
            /** Username */
            username?: string | null;
            /** Telefono */
            telefono?: string | null;
            /** Role Ids */
            role_ids?: string[] | null;
        };
        /** AssignPermissionsRequest */
        AssignPermissionsRequest: {
            /** Permission Ids */
            permission_ids: string[];
        };
        /** AuditLogPageSchema */
        AuditLogPageSchema: {
            /** Items */
            items?: components["schemas"]["AuditLogSchema"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Per Page */
            per_page: number;
            /** Total Pages */
            total_pages: number;
        };
        /** AuditLogSchema */
        AuditLogSchema: {
            /** Id */
            id: string;
            /** Empresa Id */
            empresa_id: string;
            /** Module */
            module: string;
            /** Action */
            action: string;
            /** Description */
            description: string;
            /** Level */
            level: string;
            /** User Id */
            user_id?: string | null;
            /** Actor Label */
            actor_label?: string | null;
            /** Affected Table */
            affected_table?: string | null;
            /** Record Id */
            record_id?: string | null;
            /** Previous Data */
            previous_data?: {
                [key: string]: unknown;
            } | null;
            /** New Data */
            new_data?: {
                [key: string]: unknown;
            } | null;
            /** Source Ip */
            source_ip?: string | null;
            /** User Agent */
            user_agent?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** CambiarPasswordUsuarioRequest */
        CambiarPasswordUsuarioRequest: {
            /** New Password */
            new_password: string;
            /**
             * Must Change
             * @default true
             */
            must_change: boolean;
        };
        /** ChangePasswordSchema */
        ChangePasswordSchema: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** CrearUsuarioRequest */
        CrearUsuarioRequest: {
            /** Nombre */
            nombre: string;
            /** Apellido */
            apellido: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Username */
            username: string;
            /** Password */
            password: string;
            /** Telefono */
            telefono?: string | null;
            /** Role Ids */
            role_ids: string[];
        };
        /** CreateRoleRequest */
        CreateRoleRequest: {
            /** Name */
            name: string;
            /** Codigo */
            codigo: string;
            /** Description */
            description?: string | null;
        };
        /** EmpresaCreateData */
        EmpresaCreateData: {
            /** Nit */
            nit?: string | null;
            /** Razon Social */
            razon_social: string;
            /** Nombre Comercial */
            nombre_comercial: string;
            /** Slug */
            slug: string;
            /** Email */
            email?: string | null;
            /** Telefono */
            telefono?: string | null;
            /** Direccion */
            direccion?: string | null;
            /** Ciudad */
            ciudad?: string | null;
            /** Logo Url */
            logo_url?: string | null;
        };
        /** EmpresaPageResponse */
        EmpresaPageResponse: {
            /** Items */
            items: components["schemas"]["EmpresaResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Per Page */
            per_page: number;
            /** Total Pages */
            total_pages: number;
        };
        /** EmpresaResponse */
        EmpresaResponse: {
            /** Id */
            id: string;
            /** Nit */
            nit?: string | null;
            /** Razon Social */
            razon_social: string;
            /** Nombre Comercial */
            nombre_comercial: string;
            /** Slug */
            slug: string;
            /** Email */
            email?: string | null;
            /** Telefono */
            telefono?: string | null;
            /** Direccion */
            direccion?: string | null;
            /** Ciudad */
            ciudad?: string | null;
            /** Logo Url */
            logo_url?: string | null;
            /** Activo */
            activo: boolean;
            /**
             * Fecha Registro
             * Format: date-time
             */
            fecha_registro: string;
            suscripcion?: components["schemas"]["SubscriptionResponse"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** EmpresaUpdateRequest */
        EmpresaUpdateRequest: {
            /** Nit */
            nit?: string | null;
            /** Razon Social */
            razon_social?: string | null;
            /** Nombre Comercial */
            nombre_comercial?: string | null;
            /** Slug */
            slug?: string | null;
            /** Email */
            email?: string | null;
            /** Telefono */
            telefono?: string | null;
            /** Direccion */
            direccion?: string | null;
            /** Ciudad */
            ciudad?: string | null;
            /** Logo Url */
            logo_url?: string | null;
        };
        /** ForgotPasswordResponseSchema */
        ForgotPasswordResponseSchema: {
            /** Message */
            message: string;
            /** Reset Token */
            reset_token?: string | null;
        };
        /** ForgotPasswordSchema */
        ForgotPasswordSchema: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Empresa Slug */
            empresa_slug: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InitialAdminData */
        InitialAdminData: {
            /** Nombre */
            nombre: string;
            /** Apellido */
            apellido: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Username */
            username: string;
            /** Password */
            password: string;
            /** Telefono */
            telefono?: string | null;
        };
        /** LoginSchema */
        LoginSchema: {
            /** Empresa Slug */
            empresa_slug: string;
            /** Email */
            email?: string | null;
            /** Username */
            username?: string | null;
            /** Password */
            password: string;
        };
        /** MessageResponse */
        MessageResponse: {
            /** Message */
            message: string;
        };
        /** MessageSchema */
        MessageSchema: {
            /** Message */
            message: string;
        };
        /** MiEmpresaUpdateRequest */
        MiEmpresaUpdateRequest: {
            /** Nombre Comercial */
            nombre_comercial?: string | null;
            /** Email */
            email?: string | null;
            /** Telefono */
            telefono?: string | null;
            /** Direccion */
            direccion?: string | null;
            /** Ciudad */
            ciudad?: string | null;
            /** Logo Url */
            logo_url?: string | null;
        };
        /** ParametroEmpresaResponse */
        ParametroEmpresaResponse: {
            /** Codigo */
            codigo: string;
            /** Nombre */
            nombre: string;
            /** Tipo Valor */
            tipo_valor: string;
            /** Descripcion */
            descripcion?: string | null;
            /** Valor Id */
            valor_id?: string | null;
            /** Valor */
            valor?: string | null;
            /** Norma Legal */
            norma_legal?: string | null;
            /** Vigente Desde */
            vigente_desde?: string | null;
            /** Vigente Hasta */
            vigente_hasta?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /** PermissionSchema */
        PermissionSchema: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Resource */
            resource: string;
            /** Action */
            action: string;
            /** Description */
            description?: string | null;
        };
        /** PlanCreateRequest */
        PlanCreateRequest: {
            /** Nombre */
            nombre: string;
            /** Precio Mensual */
            precio_mensual: number | string;
            /** Max Empleados */
            max_empleados: number;
            /** Modulos */
            modulos?: string[];
            /**
             * Activo
             * @default true
             */
            activo: boolean;
        };
        /** PlanResponse */
        PlanResponse: {
            /** Id */
            id: string;
            /** Nombre */
            nombre: string;
            /** Precio Mensual */
            precio_mensual: string;
            /** Max Empleados */
            max_empleados: number;
            /** Modulos */
            modulos: unknown[];
            /** Activo */
            activo: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** PlanUpdateRequest */
        PlanUpdateRequest: {
            /** Nombre */
            nombre?: string | null;
            /** Precio Mensual */
            precio_mensual?: number | string | null;
            /** Max Empleados */
            max_empleados?: number | null;
            /** Modulos */
            modulos?: string[] | null;
            /** Activo */
            activo?: boolean | null;
        };
        /** PlatformAdminResponse */
        PlatformAdminResponse: {
            /** Id */
            id: string;
            /** Nombre */
            nombre: string;
            /** Apellido */
            apellido: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Username */
            username: string;
            /** Activo */
            activo: boolean;
            /** Email Verified */
            email_verified: boolean;
            /** Ultimo Acceso */
            ultimo_acceso?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PlatformAuditPageResponse */
        PlatformAuditPageResponse: {
            /** Items */
            items: components["schemas"]["PlatformAuditResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Per Page */
            per_page: number;
            /** Total Pages */
            total_pages: number;
        };
        /** PlatformAuditResponse */
        PlatformAuditResponse: {
            /** Id */
            id: string;
            /** Admin Id */
            admin_id?: string | null;
            /** Actor Etiqueta */
            actor_etiqueta?: string | null;
            /** Modulo */
            modulo: string;
            /** Accion */
            accion: string;
            /** Nivel */
            nivel: string;
            /** Descripcion */
            descripcion: string;
            /** Tabla Afectada */
            tabla_afectada?: string | null;
            /** Registro Id */
            registro_id?: string | null;
            /** Datos Previos */
            datos_previos?: {
                [key: string]: unknown;
            } | null;
            /** Datos Nuevos */
            datos_nuevos?: {
                [key: string]: unknown;
            } | null;
            /** Ip Origen */
            ip_origen?: string | null;
            /** User Agent */
            user_agent?: string | null;
            /**
             * Fecha
             * Format: date-time
             */
            fecha: string;
        };
        /** PlatformChangePasswordRequest */
        PlatformChangePasswordRequest: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** PlatformLoginRequest */
        PlatformLoginRequest: {
            /** Login */
            login: string;
            /** Password */
            password: string;
        };
        /** PlatformRefreshRequest */
        PlatformRefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** PlatformTokenResponse */
        PlatformTokenResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
        };
        /** ProvisionEmpresaRequest */
        ProvisionEmpresaRequest: {
            empresa: components["schemas"]["EmpresaCreateData"];
            /** Plan Id */
            plan_id: string;
            /**
             * Fecha Inicio
             * Format: date
             */
            fecha_inicio: string;
            /** Fecha Fin */
            fecha_fin?: string | null;
            administrador: components["schemas"]["InitialAdminData"];
        };
        /** ProvisionEmpresaResponse */
        ProvisionEmpresaResponse: {
            empresa: components["schemas"]["EmpresaResponse"];
            /** Administrador Id */
            administrador_id: string;
            /**
             * Administrador Email
             * Format: email
             */
            administrador_email: string;
            /** Verification Email Sent */
            verification_email_sent: boolean;
        };
        /** RefreshTokenSchema */
        RefreshTokenSchema: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** ResendVerificationSchema */
        ResendVerificationSchema: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Empresa Slug */
            empresa_slug: string;
        };
        /** ResetPasswordSchema */
        ResetPasswordSchema: {
            /** Token */
            token: string;
            /** New Password */
            new_password: string;
        };
        /** RoleSchema */
        RoleSchema: {
            /** Id */
            id: string;
            /** Empresa Id */
            empresa_id: string;
            /** Name */
            name: string;
            /** Codigo */
            codigo: string;
            /** Description */
            description?: string | null;
            /** Is Active */
            is_active: boolean;
            /** Permissions */
            permissions?: components["schemas"]["PermissionSchema"][];
        };
        /** SubscriptionPageResponse */
        SubscriptionPageResponse: {
            /** Items */
            items: components["schemas"]["SubscriptionResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Per Page */
            per_page: number;
            /** Total Pages */
            total_pages: number;
        };
        /** SubscriptionResponse */
        SubscriptionResponse: {
            /** Id */
            id: string;
            /** Empresa Id */
            empresa_id: string;
            /** Empresa Nombre */
            empresa_nombre?: string | null;
            plan: components["schemas"]["PlanResponse"];
            /**
             * Fecha Inicio
             * Format: date
             */
            fecha_inicio: string;
            /** Fecha Fin */
            fecha_fin?: string | null;
            /** Activo */
            activo: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SubscriptionUpdateRequest */
        SubscriptionUpdateRequest: {
            /** Plan Id */
            plan_id: string;
            /**
             * Fecha Inicio
             * Format: date
             */
            fecha_inicio: string;
            /** Fecha Fin */
            fecha_fin?: string | null;
        };
        /** TokenPairSchema */
        TokenPairSchema: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in?: number | null;
            /**
             * Must Change Password
             * @default false
             */
            must_change_password: boolean;
        };
        /** UpdateRoleRequest */
        UpdateRoleRequest: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** UserSchema */
        UserSchema: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Empresa Id */
            empresa_id?: string | null;
            /** Username */
            username?: string | null;
            /** Roles */
            roles?: string[];
            /** Is Active */
            is_active: boolean;
            /** Email Verified */
            email_verified: boolean;
            /**
             * Must Change Password
             * @default false
             */
            must_change_password: boolean;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /** UsuarioPageResponse */
        UsuarioPageResponse: {
            /** Items */
            items: components["schemas"]["UsuarioResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Per Page */
            per_page: number;
            /** Total Pages */
            total_pages: number;
        };
        /** UsuarioResponse */
        UsuarioResponse: {
            /** Id */
            id: string;
            /** Empresa Id */
            empresa_id: string;
            /** Nombre */
            nombre: string;
            /** Apellido */
            apellido: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Username */
            username: string;
            /** Telefono */
            telefono?: string | null;
            /** Is Active */
            is_active: boolean;
            /** Email Verified */
            email_verified: boolean;
            /** Must Change Password */
            must_change_password: boolean;
            /** Failed Login Attempts */
            failed_login_attempts: number;
            /** Locked Until */
            locked_until?: string | null;
            /** Roles */
            roles?: string[];
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerifyEmailSchema */
        VerifyEmailSchema: {
            /** Token */
            token: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_health_api_v1_auth_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    login_user_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_token_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_user_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    current_user_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSchema"];
                };
            };
        };
    };
    forgot_password_api_v1_auth_password_forgot_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForgotPasswordResponseSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_password_api_v1_auth_password_change_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resend_email_verification_api_v1_auth_email_verification_resend_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResendVerificationSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_email_api_v1_auth_email_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_api_v1_auth_password_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_logs_api_v1_bitacora_get: {
        parameters: {
            query?: {
                user_id?: string | null;
                module?: string | null;
                action?: string | null;
                start_date?: string | null;
                end_date?: string | null;
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogPageSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_audit_log_api_v1_bitacora__audit_log_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                audit_log_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_parametros_empresa_api_v1_empresa_parametros_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParametroEmpresaResponse"][];
                };
            };
        };
    };
    actualizar_parametro_empresa_api_v1_empresa_parametros__codigo__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                codigo: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActualizarParametroEmpresaRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParametroEmpresaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_empresa_api_v1_mi_empresa_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmpresaResponse"];
                };
            };
        };
    };
    update_my_empresa_api_v1_mi_empresa_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MiEmpresaUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmpresaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_subscription_api_v1_mi_empresa_suscripcion_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionResponse"];
                };
            };
        };
    };
    list_my_parameters_api_v1_mi_empresa_parametros_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParametroEmpresaResponse"][];
                };
            };
        };
    };
    update_my_parameter_api_v1_mi_empresa_parametros__codigo__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                codigo: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActualizarParametroEmpresaRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParametroEmpresaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    platform_login_api_v1_platform_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlatformLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformTokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    platform_refresh_api_v1_platform_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlatformRefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformTokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    platform_logout_api_v1_platform_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlatformRefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    platform_me_api_v1_platform_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformAdminResponse"];
                };
            };
        };
    };
    platform_change_password_api_v1_platform_auth_password_change_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlatformChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_empresas_api_v1_platform_empresas_get: {
        parameters: {
            query?: {
                search?: string | null;
                activo?: boolean | null;
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmpresaPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    provision_empresa_api_v1_platform_empresas_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProvisionEmpresaRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvisionEmpresaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_empresa_api_v1_platform_empresas__empresa_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                empresa_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmpresaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_empresa_api_v1_platform_empresas__empresa_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                empresa_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmpresaUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmpresaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_empresa_api_v1_platform_empresas__empresa_id__activar_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                empresa_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmpresaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suspend_empresa_api_v1_platform_empresas__empresa_id__suspender_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                empresa_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmpresaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_planes_api_v1_platform_planes_get: {
        parameters: {
            query?: {
                activo?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_plan_api_v1_platform_planes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plan_api_v1_platform_planes__plan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_plan_api_v1_platform_planes__plan_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_subscriptions_api_v1_platform_suscripciones_get: {
        parameters: {
            query?: {
                activo?: boolean | null;
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_subscription_api_v1_platform_empresas__empresa_id__suscripcion_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                empresa_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_subscription_api_v1_platform_empresas__empresa_id__suscripcion_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                empresa_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscriptionUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_platform_audit_api_v1_platform_bitacora_get: {
        parameters: {
            query?: {
                module?: string | null;
                action?: string | null;
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformAuditPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_platform_audit_api_v1_platform_bitacora__audit_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                audit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformAuditResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_roles_api_v1_roles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleSchema"][];
                };
            };
        };
    };
    create_role_api_v1_roles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_role_api_v1_roles__role_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_role_api_v1_roles__role_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_role_api_v1_roles__role_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRoleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_permissions_api_v1_roles__role_id__permissions_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignPermissionsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_usuarios_api_v1_usuarios_get: {
        parameters: {
            query?: {
                search?: string | null;
                is_active?: boolean | null;
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_usuario_api_v1_usuarios_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearUsuarioRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_usuario_api_v1_usuarios__usuario_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                usuario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    actualizar_usuario_api_v1_usuarios__usuario_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                usuario_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActualizarUsuarioRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activar_usuario_api_v1_usuarios__usuario_id__activar_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                usuario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    desactivar_usuario_api_v1_usuarios__usuario_id__desactivar_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                usuario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cambiar_password_usuario_api_v1_usuarios__usuario_id__password_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                usuario_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CambiarPasswordUsuarioRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    desbloquear_usuario_api_v1_usuarios__usuario_id__desbloquear_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                usuario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
